name: dockerImage

on:
  workflow_run:
    workflows: ["Go"]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/api-image:latest .
    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/api-image:latest

